compute_environment: LOCAL_MACHINE
distributed_type: 'MULTI_GPU'
gpu_ids: '2,3'
machine_rank: 0
main_process_port: 29500
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false


